using System.Linq;
using Content.Shared.CCVar;
using Content.Shared.Radio;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Prototypes;

namespace Content.Client.UserInterface.Systems.Chat.Controls;

[GenerateTypedNameReferences]
public sealed partial class RadioFilterWindow : DefaultWindow
{
    private readonly IConfigurationManager _cfg;
    private readonly HashSet<string> _filteredChannels = new();

    /// <summary>Fired whenever a channel's visibility is toggled.</summary>
    public event Action? OnFilterChanged;

    public RadioFilterWindow()
    {
        RobustXamlLoader.Load(this);
        _cfg = IoCManager.Resolve<IConfigurationManager>();

        // Load saved filtered channels from config.
        var saved = _cfg.GetCVar(CCVars.ChatFilteredRadioChannels);
        if (!string.IsNullOrEmpty(saved))
        {
            foreach (var id in saved.Split(','))
            {
                if (!string.IsNullOrWhiteSpace(id))
                    _filteredChannels.Add(id.Trim());
            }
        }

        // Build a checkbox per radio channel prototype, sorted by name.
        var protoMan = IoCManager.Resolve<IPrototypeManager>();
        var channels = protoMan.EnumeratePrototypes<RadioChannelPrototype>()
            .OrderBy(c => c.LocalizedName)
            .ToList();

        foreach (var channel in channels)
        {
            var checkbox = new CheckBox
            {
                Text = channel.LocalizedName,
                Pressed = !_filteredChannels.Contains(channel.ID),
            };

            // Capture loop variable.
            var channelId = channel.ID;
            checkbox.OnToggled += args => OnCheckboxToggled(channelId, args.Pressed);
            RadioChannelVBox.AddChild(checkbox);
        }
    }

    /// <summary>Returns true if the given channel should be shown in the chat.</summary>
    public bool IsChannelVisible(string channelId) => !_filteredChannels.Contains(channelId);

    private void OnCheckboxToggled(string channelId, bool pressed)
    {
        if (pressed)
            _filteredChannels.Remove(channelId);
        else
            _filteredChannels.Add(channelId);

        SaveToConfig();
        OnFilterChanged?.Invoke();
    }

    private void SaveToConfig()
    {
        _cfg.SetCVar(CCVars.ChatFilteredRadioChannels, string.Join(',', _filteredChannels));
    }
}
